### ISSUE TITLE
deviceID should be received as an argument

### ISSUE THREAD

**Issue by moizhusnain** [grandeurtech/grandeurcloud-hardware-sdk#1]
In functions like getSummary the deviceID should be received directly in argument instead of first wrapping it in JSON object. That is the way we are receiving deviceID in JS SDK.

**Comment by abdullahgrey** [comment]
Here in Hardware SDK, **deviceID** is received while initializing Apollo through `init(deviceID, apiKey, token, ssid, passphrase)`. Therefore, we do not need to receive it again.
